# Unit in [um]

JJ:
  type: "manhattan"
  squid: false
  photolitho: false
  bandage: false

  # Connect two transmons
  entangle:
    - pairs: [0, 1]
      path:
        radius: 75
        path_type: 'U'
        length1: 195
        smooth_options:
          corner_fun: "pp.arc"
    - pairs: [2, 3]          
      path:
        path_type: 'straight'

  rounding: 0 # 0.05
  finger:
    layer: 1
    length: 10
    width: 0.15
    rounding: 0
  pad_box:
    width: 2.0
    length: 10
    gap: 4.0
  bridge:
    width: 0.9
  taper:
    width1: 10
    width2: 40
    length: 100
    gap: 10